hablas/urls.py
from django.urls import path

from .views import *

app_name = 'hablas'
urlpatterns = [
    path('', ListHablasView.as_view(), name='index'),
    path('create/', CreateHablaView.as_view(), name='create'),
    path('search/', search_hablas, name='search'),
    path('<str:habla_cattegory>/search_by_tag/', search_hablas_by_tag, name='search_by_tag'),
    path('<int:pk>/', DetailHablaView.as_view(), name='detail'),
    path('<int:habla_id>/delete/', delete_habla, name='delete'),
    path('<int:pk>/edit/', EditHablaView.as_view(), name='edit'),
    path('<int:habla_id>/like/', like_habla, name='like'),
    path('<int:habla_id>/create_comment/', create_comment, name ='create_comment')
]

hablasite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('hablas.urls')),
    path('admin/', admin.site.urls),
]

moviesite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('movies/', include('movies.urls')),
    path('admin/', admin.site.urls),
]

hablas/models.py
from django.db import models
from django.conf import settings


class Habla(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    text = models.CharField(max_length=255)
    post_date = models.DateTimeField()
    likes  = models.IntegerField(default=0)
    cattegory = models.CharField(max_length=255)
    
    def __str__(self):
        return f'{self.text} - ({self.post_date}) - ({self.author.username}) - ({self.cattegory})'


class Comment(models.Model):
    author = models.ForeignKey(settings.AUTH_USER_MODEL,
                               on_delete=models.CASCADE)
    post_date = models.DateTimeField()
    comment_text = models.CharField(max_length=255)
    habla = models.ForeignKey(Habla, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.comment_text}" - ({self.post_date}) - ({self.author.username})'

hablas/forms.py
from django.forms import ModelForm
from .models import *

class HablaForm(ModelForm):
    class Meta:
        model = Habla
        fields = [
            'author',
            'text',
            'cattegory'
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Habla',
            'cattegory': 'Categorias'
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = [
            'author',
            'comment_text',
        ]
        labels = {
            'author': 'Usuário',
            'comment_text': 'Comentário',
        }

hablas/views.py
from django.http import HttpResponseRedirect
from django.views import generic
from django.urls import reverse, reverse_lazy
from django.contrib.auth.models import User
from .models import *
from .forms import *
from django.shortcuts import render, redirect
from datetime import datetime

class ListHablasView(generic.ListView):
    model = Habla
    template_name = 'hablas/index.html'
    context_object_name = 'habla_list'

    def get_queryset(self):
        return reversed(Habla.objects.all())

class DetailHablaView(generic.DetailView):
    model = Habla
    template_name = 'hablas/detail.html'
    context_object_name = 'habla'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        comment_data = Comment.objects.filter(habla=self.object)
        context['comment_list'] = reversed(comment_data)
        return context

class CreateHablaView(generic.CreateView):
    model = Habla
    form_class = HablaForm
    template_name = 'hablas/create.html'
    success_url = reverse_lazy('hablas:index') 

    def form_valid(self, form):
        form.instance.post_date = datetime.now()
        return super().form_valid(form)

def delete_habla(request,habla_id):
    habla = Habla.objects.get(id=habla_id)
    habla.delete()    
    return redirect('hablas:index')
    
class EditHablaView(generic.UpdateView):
    model = Habla
    form_class = HablaForm
    template_name = 'hablas/edit.html'

    def form_valid(self, form):
        habla = form.save(commit=False)
        habla.post_date = datetime.now()
        habla.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('hablas:detail', kwargs={'pk': self.object.pk})
    
def like_habla(request,habla_id):    
    habla = Habla.objects.get(id=habla_id)
    habla.likes+=1
    habla.save()
    return redirect('hablas:index')
    
    
def create_comment(request, habla_id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment_text = request.POST['comment_text']
            author_id = request.POST['author']
            comment_author = User.objects.get(id=author_id)
            habla = Habla.objects.get(id=habla_id) 
            comment = Comment(comment_text=comment_text,
                          post_date = datetime.now(),
                          habla = habla,
                        author = comment_author )
            comment.save()
            return HttpResponseRedirect(
                reverse('hablas:detail', args=(habla.id, )))
    else:
        form = CommentForm()
        context = {'form': form}
        return render(request, 'hablas/create_comment.html', context)
    


def search_hablas(request):
    context={}
    if request.GET.get("query", False):
        search_term = request.GET["query"].lower()
        context = {'search_term':search_term}
        habla_list = Habla.objects.filter(cattegory__icontains=search_term)
        if len(habla_list)> 0:
            context["habla_list"]= (habla_list)
    return render(request, "hablas/search.html", context)

def search_hablas_by_tag(request, habla_cattegory):
    context = {'search_term':habla_cattegory}
    habla_list = Habla.objects.filter(cattegory__icontains=habla_cattegory)
    if len(habla_list)> 0:
        context["habla_list"]= (habla_list)
    return render(request, "hablas/search.html", context)

hablas/templates/hablas/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Habla</h2>
<form class='habla_creation' method="post" action="{% url 'hablas:create' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button class='save_button'type="submit">Criar</button>
</form>

{% endblock content %}

hablas/templates/hablas/create_comment.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir novo comentário</h2>
<form class='habla_creation' method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class='save_button'type="submit">Criar</button>
</form>

{% endblock content %}

hablas/templates/hablas/detail.html
{% extends 'base.html' %}

{% block title %}

{% endblock title %}

{% block content %}

<article class="card">
    <h3 class="'habla_text">{{ habla.author }} postou:</h3>
    <h2>{{habla.text}} </h2>
    <h3>{{ habla.post_date }} </h3>
    <h3>{{ habla.likes }} curtidas </h3>
    {%if habla.cattegory %}
    <h3>
        #{{ habla.cattegory }}</h3>
        {% endif %}
    <section class ='habla_buttons'>
        <a style="background-color: blue;" class="habla_button" href="{% url 'hablas:create_comment' habla.id %}">Comentar</a>
    </section>
</article>

{% for comment in comment_list %}
    <article class="card">
        <h3>{{ comment.author }} comentou: </h3>
        <h2>{{comment.comment_text}}</h2>
        <h3>{{ comment.post_date }} </h3>
    </article>
    {% endfor %}
{% endblock content %}

hablas/templates/hablas/edit.html
{% extends 'base.html' %}

{% block content %}
<form class='habla_creation' method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class='save_button'type="submit">Salvar</button>
</form>

{% endblock content %}

hablas/templates/hablas/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Últimos Hablas</h2>
{%if habla_list %}
<section class="lista-de-cards">
    {% for habla in object_list %}
    <article class="card">
        <h1 class="'habla_text">{{ habla.author }} postou:</h1>
        <h2>{{habla.text}} </h2>
        <h1>{{ habla.post_date }} </h1>
        <h1>{{ habla.likes }} curtidas </h1>
        {%if habla.cattegory %}
        <a style="background-color: rgb(169, 169, 52);" 
            class="habla_button" href="{% url 'hablas:search_by_tag' habla.cattegory %}">
            #{{ habla.cattegory }}</a>
            {% endif %}
        <section class ='habla_buttons'>
            <a style="background-color: blue;" class="habla_button" href="{% url 'hablas:detail' habla.id %}">Ver mais</a>
            <a style="background-color: red;" class="habla_button" href="{% url 'hablas:delete' habla.id %}">Excluir</a>
            <a style="background-color:saddlebrown;" class="habla_button" href="{% url 'hablas:edit' habla.id %}">Editar</a>
            <a style="background-color: green;" class="habla_button" href="{% url 'hablas:like' habla.id %}">Curtir</a>
        </section>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum Habla.</p>
{% endif %}

{% endblock content %}

hablas/templates/hablas/search.html
{% extends 'base.html' %}
{% block content %}
{%if habla_list %}
<h2>Resultados para {{search_term}}:</h2>
<section class="lista-de-cards">
    {% for habla in habla_list %}
    <article class="card">
        <h1 class="'habla_text">{{ habla.author }} postou:</h1>
        <h2>{{habla.text}} </h2>
        <h1>{{ habla.post_date }} </h1>
        <h1>{{ habla.likes }} curtidas </h1>
        {%if habla.cattegory %}
        <a style="background-color: rgb(169, 169, 52);" 
            class="habla_button" href="{% url 'hablas:search_by_tag' habla.cattegory %}">
            #{{ habla.cattegory }}</a>
            {% endif %}
        <section class ='habla_buttons'>
            <a style="background-color: blue;" class="habla_button" href="{% url 'hablas:detail' habla.id %}">Ver mais</a>
            <a style="background-color: red;" class="habla_button" href="{% url 'hablas:delete' habla.id %}">Excluir</a>
            <a style="background-color:saddlebrown;" class="habla_button" href="{% url 'hablas:edit' habla.id %}">Editar</a>
            <a style="background-color: green;" class="habla_button" href="{% url 'hablas:like' habla.id %}">Curtir</a>
        </section>
    </article>
    {% endfor %}
</section>
{% else %}
<h2>Não foram encontrados Hablas para {{search_term}}.</h2>
{% endif %}
{% endblock content %}

movies/templates/movies/create.html
{% extends 'base.html' %}

{% block content %}
<h2>Inserir Novo Filme</h2>
<form method="POST" action="{% url 'movies:create' %}">
    {% csrf_token %}
    <p>
        <label for="id_name">Título:</label>
        <input type="text" name="name" id="id_name" />
    </p>
    <p>
        <label for="id_release_year">Ano de Lançamento:</label>
        <input type="number" name="release_year" id="id_release_year" />
    </p>
    <p>
        <label for="id_poster_url">URL do Poster:</label>
        <input type="url" name="poster_url" id="id_poster_url" />
    </p>
    <button type="submit">Criar</button>
</form>

{% endblock content %}

movies/templates/movies/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Filmes por Nome</h2>
<form action="{% url 'movies:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if movie_list %}
<section class="lista-de-cards">
    {% for movie in movie_list %}
    <article class="card">
        <img src="{{ movie.poster_url }}" alt="Poster do filme {{ movie.name}}">
        <p>{{ movie.name }} ({{ movie.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum filme para a busca.</p>
{% endif %}

{% endblock content %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Habla!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'hablas:index' %}"> <img src="{% static 'logo.svg' %}"> </a>
        <a class = "create_habla" href="{% url 'hablas:create' %}">Clique para Hablar</a>
        <form class='search_form'action="{% url 'hablas:search' %}">
            <h3>Buscar categorias</h3>
            <p>
                <input class="input_cattegory" type="text" name="query" id="id_query" />
            </p>
            <button class="search" type="submit">Buscar</button>
        </form>        
    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2023</small>
        </p>
    </footer>
</body>

</html>